# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptive_nonlocal_means_denoising <- function(ima, dims, v, f, h) {
    .Call('_utils4ni_adaptive_nonlocal_means_denoising', PACKAGE = 'utils4ni', ima, dims, v, f, h)
}

cCreateMask <- function(ima, dims, c, medias) {
    .Call('_utils4ni_cCreateMask', PACKAGE = 'utils4ni', ima, dims, c, medias)
}

cgradientmodule <- function(ima, dims) {
    .Call('_utils4ni_cgradientmodule', PACKAGE = 'utils4ni', ima, dims)
}

connected_components <- function(image) {
    .Call('_utils4ni_connected_components', PACKAGE = 'utils4ni', image)
}

cTruncado <- function(ima, dims) {
    .Call('_utils4ni_cTruncado', PACKAGE = 'utils4ni', ima, dims)
}

cvolfilter2d <- function(ima, dims, v) {
    .Call('_utils4ni_cvolfilter2d', PACKAGE = 'utils4ni', ima, dims, v)
}

defuzzify <- function(image) {
    .Call('_utils4ni_defuzzify', PACKAGE = 'utils4ni', image)
}

extend_labels <- function(pIn, maskImage) {
    .Call('_utils4ni_extend_labels', PACKAGE = 'utils4ni', pIn, maskImage)
}

map_ids_workhorse <- function(x, source, target) {
    .Call('_utils4ni_map_ids_workhorse', PACKAGE = 'utils4ni', x, source, target)
}

map_extra_classes <- function(x, source, remaining) {
    .Call('_utils4ni_map_extra_classes', PACKAGE = 'utils4ni', x, source, remaining)
}

mask_values <- function(input, low, high, in_val, out_val) {
    .Call('_utils4ni_mask_values', PACKAGE = 'utils4ni', input, low, high, in_val, out_val)
}

get_neighbours <- function(array, width) {
    .Call('_utils4ni_get_neighbours', PACKAGE = 'utils4ni', array, width)
}

fast_read_nifti <- function(filename) {
    .Call('_utils4ni_fast_read_nifti', PACKAGE = 'utils4ni', filename)
}

regularize <- function(image, kernel) {
    .Call('_utils4ni_regularize', PACKAGE = 'utils4ni', image, kernel)
}

sum_by_ROI <- function(labelled, values) {
    .Call('_utils4ni_sum_by_ROI', PACKAGE = 'utils4ni', labelled, values)
}

max_by_ROI <- function(labelled, values) {
    .Call('_utils4ni_max_by_ROI', PACKAGE = 'utils4ni', labelled, values)
}

min_by_ROI <- function(labelled, values) {
    .Call('_utils4ni_min_by_ROI', PACKAGE = 'utils4ni', labelled, values)
}

count_by_ROI <- function(labelled) {
    .Call('_utils4ni_count_by_ROI', PACKAGE = 'utils4ni', labelled)
}

mean_by_ROI <- function(labelled, values) {
    .Call('_utils4ni_mean_by_ROI', PACKAGE = 'utils4ni', labelled, values)
}

segmentation <- function(image, otsu_estimates) {
    .Call('_utils4ni_segmentation', PACKAGE = 'utils4ni', image, otsu_estimates)
}

