# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptive_nonlocal_means_denoising <- function(ima, dims, v, f, h) {
    .Call('_utils4ni_adaptive_nonlocal_means_denoising', PACKAGE = 'utils4ni', ima, dims, v, f, h)
}

cCreateMask <- function(ima, dims, c, medias) {
    .Call('_utils4ni_cCreateMask', PACKAGE = 'utils4ni', ima, dims, c, medias)
}

cgradientmodule <- function(ima, dims) {
    .Call('_utils4ni_cgradientmodule', PACKAGE = 'utils4ni', ima, dims)
}

confusion_matrix <- function(label1, label2) {
    .Call('_utils4ni_confusion_matrix', PACKAGE = 'utils4ni', label1, label2)
}

connected_components <- function(image) {
    .Call('_utils4ni_connected_components', PACKAGE = 'utils4ni', image)
}

cTruncado <- function(ima, dims) {
    .Call('_utils4ni_cTruncado', PACKAGE = 'utils4ni', ima, dims)
}

cvolfilter2d <- function(ima, dims, v) {
    .Call('_utils4ni_cvolfilter2d', PACKAGE = 'utils4ni', ima, dims, v)
}

defuzzify <- function(image, ncores = 1L) {
    .Call('_utils4ni_defuzzify', PACKAGE = 'utils4ni', image, ncores)
}

extend_labels <- function(pIn, maskImage) {
    .Call('_utils4ni_extend_labels', PACKAGE = 'utils4ni', pIn, maskImage)
}

map_ids_workhorse <- function(x, source, target) {
    .Call('_utils4ni_map_ids_workhorse', PACKAGE = 'utils4ni', x, source, target)
}

map_extra_classes <- function(x, source, remaining) {
    .Call('_utils4ni_map_extra_classes', PACKAGE = 'utils4ni', x, source, remaining)
}

mask_values <- function(input, low, high, in_val, out_val) {
    .Call('_utils4ni_mask_values', PACKAGE = 'utils4ni', input, low, high, in_val, out_val)
}

get_neighbours <- function(array, width) {
    .Call('_utils4ni_get_neighbours', PACKAGE = 'utils4ni', array, width)
}

fast_read_nifti <- function(filename) {
    .Call('_utils4ni_fast_read_nifti', PACKAGE = 'utils4ni', filename)
}

read_nifti_batch_4d <- function(filenames) {
    .Call('_utils4ni_read_nifti_batch_4d', PACKAGE = 'utils4ni', filenames)
}

read_nifti <- function(filename) {
    .Call('_utils4ni_read_nifti', PACKAGE = 'utils4ni', filename)
}

constrained_init_memory <- function(dims, n_templates, patch_size, search_size, voxel_lookup_table, kANN, ncores = 1L) {
    invisible(.Call('_utils4ni_constrained_init_memory', PACKAGE = 'utils4ni', dims, n_templates, patch_size, search_size, voxel_lookup_table, kANN, ncores))
}

patches_similarity_memory <- function(input_image, template_filenames, actual_voxels, voxel_lookup_table, patch_neighbours, kANN, similarities, ncores = 1L) {
    invisible(.Call('_utils4ni_patches_similarity_memory', PACKAGE = 'utils4ni', input_image, template_filenames, actual_voxels, voxel_lookup_table, patch_neighbours, kANN, similarities, ncores))
}

propagation_step_memory <- function(input_image, template_filenames, actual_voxels, voxel_lookup_table, patch_neighbours, kANN, direction, patch_size, stride, similarities, ncores = 1L) {
    invisible(.Call('_utils4ni_propagation_step_memory', PACKAGE = 'utils4ni', input_image, template_filenames, actual_voxels, voxel_lookup_table, patch_neighbours, kANN, direction, patch_size, stride, similarities, ncores))
}

constrained_random_search_memory <- function(input_image, template_filenames, actual_voxels, voxel_lookup_table, kANN, patch_size, patch_neighbours, search_size_max, similarities, max_random_neighbours, ncores = 1L) {
    invisible(.Call('_utils4ni_constrained_random_search_memory', PACKAGE = 'utils4ni', input_image, template_filenames, actual_voxels, voxel_lookup_table, kANN, patch_size, patch_neighbours, search_size_max, similarities, max_random_neighbours, ncores))
}

label_fusion_memory <- function(label_filenames, actual_voxels, voxel_lookup_table, label_ids, kANN, patch_neighbours, lambda, sigma2, match, new_voting, ncores = 2L) {
    invisible(.Call('_utils4ni_label_fusion_memory', PACKAGE = 'utils4ni', label_filenames, actual_voxels, voxel_lookup_table, label_ids, kANN, patch_neighbours, lambda, sigma2, match, new_voting, ncores))
}

obtain_candidates_memory <- function(image, template_files, patch_size, search_size, stride, max_iter, max_random_neighbours, ncores = 2L) {
    .Call('_utils4ni_obtain_candidates_memory', PACKAGE = 'utils4ni', image, template_files, patch_size, search_size, stride, max_iter, max_random_neighbours, ncores)
}

count_elegible <- function(image, patch_size, search_size, stride, voxel_lookup_table) {
    .Call('_utils4ni_count_elegible', PACKAGE = 'utils4ni', image, patch_size, search_size, stride, voxel_lookup_table)
}

count_elegible_masked <- function(image, mask, patch_size, search_size, stride, voxel_lookup_table) {
    .Call('_utils4ni_count_elegible_masked', PACKAGE = 'utils4ni', image, mask, patch_size, search_size, stride, voxel_lookup_table)
}

constrained_initialization_omp <- function(input_image, template4D, patch_size, search_size, actual_voxels, voxel_lookup_table, kANN, ncores = 1L) {
    invisible(.Call('_utils4ni_constrained_initialization_omp', PACKAGE = 'utils4ni', input_image, template4D, patch_size, search_size, actual_voxels, voxel_lookup_table, kANN, ncores))
}

all_patches_similarity_omp <- function(input_image, template4D, actual_voxels, voxel_lookup_table, patch_neighbours, kANN, similarities, method = 0L, ncores = 1L) {
    invisible(.Call('_utils4ni_all_patches_similarity_omp', PACKAGE = 'utils4ni', input_image, template4D, actual_voxels, voxel_lookup_table, patch_neighbours, kANN, similarities, method, ncores))
}

propagation_step_omp <- function(input_image, template4D, actual_voxels, voxel_lookup_table, patch_neighbours, kANN, direction, patch_size, stride, similarities, method = 0L, ncores = 1L) {
    invisible(.Call('_utils4ni_propagation_step_omp', PACKAGE = 'utils4ni', input_image, template4D, actual_voxels, voxel_lookup_table, patch_neighbours, kANN, direction, patch_size, stride, similarities, method, ncores))
}

constrained_random_search_omp <- function(input_image, template4D, actual_voxels, voxel_lookup_table, kANN, patch_size, patch_neighbours, search_size_max, similarities, max_random_neighbours, method = 0L, ncores = 1L) {
    invisible(.Call('_utils4ni_constrained_random_search_omp', PACKAGE = 'utils4ni', input_image, template4D, actual_voxels, voxel_lookup_table, kANN, patch_size, patch_neighbours, search_size_max, similarities, max_random_neighbours, method, ncores))
}

label_fusion2_omp <- function(labels4D, actual_voxels, voxel_lookup_table, label_ids, kANN, patch_neighbours, lambda, sigma2, match, new_voting, ncores = 2L) {
    invisible(.Call('_utils4ni_label_fusion2_omp', PACKAGE = 'utils4ni', labels4D, actual_voxels, voxel_lookup_table, label_ids, kANN, patch_neighbours, lambda, sigma2, match, new_voting, ncores))
}

image_fusion_omp <- function(labels4D, actual_voxels, voxel_lookup_table, kANN, patch_neighbours, lambda, sigma2, match, new_voting, voxel_candidate, ncores = 2L) {
    invisible(.Call('_utils4ni_image_fusion_omp', PACKAGE = 'utils4ni', labels4D, actual_voxels, voxel_lookup_table, kANN, patch_neighbours, lambda, sigma2, match, new_voting, voxel_candidate, ncores))
}

get_windows_at <- function(V, width, x, y, z) {
    .Call('_utils4ni_get_windows_at', PACKAGE = 'utils4ni', V, width, x, y, z)
}

results_to_volume <- function(V, width, res, counts, x, y, z) {
    invisible(.Call('_utils4ni_results_to_volume', PACKAGE = 'utils4ni', V, width, res, counts, x, y, z))
}

results_to_volume_label <- function(V, width, res, x, y, z) {
    invisible(.Call('_utils4ni_results_to_volume_label', PACKAGE = 'utils4ni', V, width, res, x, y, z))
}

results_to_volume_label_with_distance <- function(V, width, res, last_distance, x, y, z) {
    invisible(.Call('_utils4ni_results_to_volume_label_with_distance', PACKAGE = 'utils4ni', V, width, res, last_distance, x, y, z))
}

regularize <- function(image, kernel, ncores = 1L) {
    .Call('_utils4ni_regularize', PACKAGE = 'utils4ni', image, kernel, ncores)
}

sum_4d <- function(values) {
    .Call('_utils4ni_sum_4d', PACKAGE = 'utils4ni', values)
}

sum_by_ROI <- function(labelled, values) {
    .Call('_utils4ni_sum_by_ROI', PACKAGE = 'utils4ni', labelled, values)
}

max_by_ROI <- function(labelled, values) {
    .Call('_utils4ni_max_by_ROI', PACKAGE = 'utils4ni', labelled, values)
}

min_by_ROI <- function(labelled, values) {
    .Call('_utils4ni_min_by_ROI', PACKAGE = 'utils4ni', labelled, values)
}

count_by_ROI <- function(labelled) {
    .Call('_utils4ni_count_by_ROI', PACKAGE = 'utils4ni', labelled)
}

mean_by_ROI <- function(labelled, values) {
    .Call('_utils4ni_mean_by_ROI', PACKAGE = 'utils4ni', labelled, values)
}

segmentation <- function(image, otsu_estimates) {
    .Call('_utils4ni_segmentation', PACKAGE = 'utils4ni', image, otsu_estimates)
}

which_max <- function(image) {
    .Call('_utils4ni_which_max', PACKAGE = 'utils4ni', image)
}

to_categorical_volume_cpp <- function(image, unique_labels) {
    .Call('_utils4ni_to_categorical_volume_cpp', PACKAGE = 'utils4ni', image, unique_labels)
}

transform_volume <- function(V, M, target_dims, method) {
    .Call('_utils4ni_transform_volume', PACKAGE = 'utils4ni', V, M, target_dims, method)
}

deform_volume <- function(V, Dx, Dy, Dz, target_dims, method) {
    .Call('_utils4ni_deform_volume', PACKAGE = 'utils4ni', V, Dx, Dy, Dz, target_dims, method)
}

deform_volume_candidates <- function(V, Dx, Dy, Dz, target_dims, method) {
    .Call('_utils4ni_deform_volume_candidates', PACKAGE = 'utils4ni', V, Dx, Dy, Dz, target_dims, method)
}

generate_random <- function(min, max, n) {
    .Call('_utils4ni_generate_random', PACKAGE = 'utils4ni', min, max, n)
}

